apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-faker-schema
  namespace: apk
data:
  schema.graphql: |
    schema {
      query: Query
    }

    # The Query type defines the root queries that can be executed
    type Query {
      patient(id: ID!): Patient
      patients: [Patient]
      doctor(id: ID!): Doctor
      doctors: [Doctor]
    }

    # A Patient type to represent patient information
    type Patient {
      id: ID!
      name: String!
      age: Int!
      gender: String!
      contactInfo: ContactInfo
      medicalHistory: [MedicalRecord]
      appointments: [Appointment]
      medications: [Medication]
    }

    # A type to represent contact information of a patient
    type ContactInfo {
      phone: String
      email: String
      address: String
    }

    # A type to represent a medical record
    type MedicalRecord {
      date: String!
      description: String!
      doctor: Doctor
    }

    # A type to represent an appointment
    type Appointment {
      date: String!
      time: String!
      doctor: Doctor
      purpose: String
    }

    # A type to represent a medication
    type Medication {
      name: String!
      dosage: String!
      frequency: String!
    }

    # A type to represent a doctor
    type Doctor {
      id: ID!
      name: String!
      specialty: String!
      contactInfo: ContactInfo
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-faker
  namespace: apk
  labels:
    app: graphql-faker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-faker
  template:
    metadata:
      labels:
        app: graphql-faker
    spec:
      containers:
        - name: graphql-faker
          image: apisguru/graphql-faker
          args: ["--open=false", "/etc/graphql-faker/schema.graphql"]
          ports:
            - containerPort: 9002
          volumeMounts:
            - name: schema-volume
              mountPath: /etc/graphql-faker
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: schema-volume
          configMap:
            name: graphql-faker-schema
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-faker-service
  namespace: apk
spec:
  type: LoadBalancer
  ports:
    - port: 9002
      targetPort: 9002
      protocol: TCP
  selector:
    app: graphql-faker
