apiVersion: v1
kind: Service
metadata:
  name: patient-info-backend-service
spec:
  selector:
    app: patient-info-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
